function grad_E1_p2p = grad_E_shell_pen_p2p(in1)
%grad_E_shell_pen_p2p
%    grad_E1_p2p = grad_E_shell_pen_p2p(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    15-Apr-2025 16:51:37

Delta = in1(:,19);
h = in1(:,20);
x111 = in1(:,1);
x112 = in1(:,2);
x113 = in1(:,3);
x211 = in1(:,10);
x212 = in1(:,11);
x213 = in1(:,12);
t2 = Delta.*2.0;
t3 = h.*4.0;
t5 = -x211;
t6 = -x212;
t7 = -x213;
t4 = -t3;
t8 = t5+x111;
t9 = t6+x112;
t10 = t7+x113;
t11 = abs(t8);
t12 = abs(t9);
t13 = abs(t10);
t14 = t2+t4;
t15 = t11.^2;
t16 = t12.^2;
t17 = t13.^2;
t18 = t15+t16+t17;
t19 = 1.0./sqrt(t18);
grad_E1_p2p = [t14.*t19.*x111;t14.*t19.*x112;t14.*t19.*x113;0.0;0.0;0.0;0.0;0.0;0.0;t14.*t19.*x211;t14.*t19.*x212;t14.*t19.*x213;0.0;0.0;0.0;0.0;0.0;0.0];
