function grad_E2_p2p = grad_E_shell_con_p2p(in1)
%grad_E_shell_con_p2p
%    grad_E2_p2p = grad_E_shell_con_p2p(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    15-Apr-2025 16:51:40

Delta = in1(:,19);
K1 = in1(:,21);
h = in1(:,20);
x111 = in1(:,1);
x112 = in1(:,2);
x113 = in1(:,3);
x211 = in1(:,10);
x212 = in1(:,11);
x213 = in1(:,12);
t2 = h.*2.0;
t3 = 1.0./K1;
t5 = -x211;
t6 = -x212;
t7 = -x213;
t4 = -t2;
t9 = t5+x111;
t10 = t6+x112;
t11 = t7+x113;
t8 = Delta+t4;
t12 = abs(t9);
t13 = abs(t10);
t14 = abs(t11);
t15 = K1.*t8;
t16 = t12.^2;
t17 = t13.^2;
t18 = t14.^2;
t19 = -t15;
t24 = t16+t17+t18;
t20 = exp(t19);
t25 = 1.0./sqrt(t24);
t21 = t20+1.0;
t22 = log(t21);
t23 = 1.0./t21;
grad_E2_p2p = [t3.*t20.*t22.*t23.*t25.*x111.*-2.0;t3.*t20.*t22.*t23.*t25.*x112.*-2.0;t3.*t20.*t22.*t23.*t25.*x113.*-2.0;0.0;0.0;0.0;0.0;0.0;0.0;t3.*t20.*t22.*t23.*t25.*x211.*-2.0;t3.*t20.*t22.*t23.*t25.*x212.*-2.0;t3.*t20.*t22.*t23.*t25.*x213.*-2.0;0.0;0.0;0.0;0.0;0.0;0.0];
